language: node_js
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g coveralls
script:
- npm run dist
- npm run test:ci
- npm run patterns:dist
- ".githooks/deploy"
- ".githooks/pre-commit"
# Prepare for GitHub Pages deployment of the docs folder.
- rm -rf pages && cp -R docs pages && cp -R core/static/* pages
after_success:
- cat ./coverage/lcov.info | coveralls
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  # Only deploy the pages subfolder, not the whole repository.
  local_dir: pages
  # This value is stored below, encrypted with travis-encrypt.
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: lBYf1xruUYcLld1RT6WhNsF5GZTcd66lJMgizdEeiOaIne2Y1fiBTBJBiHV0drXCcrG2ObCoqa0ZBndLs7R0Pw9yfAZCK28P3xZ/T6uEhQrUf1Wi8R3HbOsVi36VA1QYV1QTb4gjf3KKAspa64730HkyHJHiFewKwhO6EGzDT1QRjgXZ9KNAgeswr+WTHEiDmxUDFuVOk61wtvagO79psyogFK7feb61AUlrIadJetM+zlT5r7jNLxDJ5tQR9IN07PDmtV3g4iTpODHqFfnoqBRE2Lh0RqwJ3W/XwWXAx4fG0p/Cit1h5KqhKAL8rG28PykFRWCKbVt/J4w+x7DAD5B4Cph0HgK1Kk6FsLCQLHM73xrF3e1j0o17K1pfhphMKtW9zb6pyUroSSeXWRqEr+QhNOISkUXoQPf8o0psw2uM3oAtg+xkrF+XxFw5vrUwlgAnPuQ93FVA52RQ/vL60fFqOPs3BEaEEpxwtT2zgEI+FEIOqSn0BVKemy4hLnY4bYm9Jss2qoIo0TdJxh0ULh0ghNs8rvl3Ppaxz7cH5ThXm4OnQAb1UE7r6RdkWey5bcWgXeQrrfq2tl/StEBjPMvziByU6kjbnqnNHvOu3JuAorYcKScQ4PSQekFXpo3e9rSqlmqtkoO+a9Qm3c1I1XBQasjNBoeuHM5ASniu6RM=
env:
  global:
    secure: c+oI98jgDmwbtWj7E4gg1I4R6qY1GSHk3gUfWJuFvZQZ33yF2rDGF3wJvG60MH5b2UHoKnroth0I00dPDlAe7qSfWivUF5Tjy3Xfyglx0PTlROuA/TcoqxVqGe/wUpQwjrC7O6nPuFgLdPksFtGctfsmk2sKEnXv0DfgQ1NE8U33BINWtvIrpYflEVbmG5xUvn3kWNtS2R076znRoDeGnAGovvgnid+c/kTigFd3sJSXm/6PJGdA8jHnI61M0oleQ/6P28gVpBmdDyziXsopC//HS7ruFLcxlNNBxWhUdrr5/Pav+LKFSpFO0ZQRjPuQ9odR3orfpmZZLzg8WzACDiBN9hk7xgv48BB/wk693RzsEBFUT73FttvjJmjqI3GFO5+m9CfEEUIsK3grU79KQaDGzVjNjx4p1wKz5bxXBEa7SwQYXw/1uM8Rec0VVNK1NPxSgxxUYjEh09uUKAycYfkNGWWeU4uIqF5laevobkJGEv8R4P9nofGDAsEkx9GC17P7LHxwklKYTVQhZTCnpedKc/oppGyv7xEisuMdKiXNw6lt/MoVDV8YjpDPgowXm+3aPT9Kovn4BaCoNMjsa9Hk+KPJe9pYGwGtBJHM7LV4gqB+LcoHgh1L3pp2BKKRA1E8ERMYgaSCO1URY0+M/PZZ0NRk1OyTbLVYaWtGNJc=
